name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install Backend Dependencies
      run: |
        cd backend
        npm install
        
    - name: Run Backend Tests
      run: |
        cd backend
        npm test
        
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install
        
    - name: Run Frontend Tests
      run: |
        cd frontend
        npm test -- --watchAll=false
