name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tarefas_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install Backend Dependencies
      run: |
        cd backend
        npm install
        
    - name: Run Backend Tests
      env:
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_HOST: localhost
        DB_PORT: 5432
        DB_DATABASE: tarefas_test
        JWT_SECRET: testsecret
      run: |
        cd backend
        npm test
        
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install
        
    - name: Run Frontend Tests
      run: |
        cd frontend
        npm test -- --watchAll=false
